FROM ruby:2.1.7

# Inspired by https://blog.codeship.com/running-rails-development-environment-docker/
RUN apt-get update && apt-get install -y \
  build-essential \
  nodejs

RUN apt-get install -y libpq-dev git unzip libgeos-dev proj-bin libproj-dev make

RUN gem install bundler -v 1.10.3

# https://github.com/Yelp/dumb-init
RUN wget --quiet https://github.com/Yelp/dumb-init/releases/download/v1.0.0/dumb-init_1.0.0_amd64.deb
RUN dpkg -i dumb-init_*.deb

COPY source /code
WORKDIR /code

RUN git log -n 1 --pretty=format:"%H" > /version
RUN bundle install

EXPOSE 3000

ENV RAILS_ENV=production

CMD [ "dumb-init", "bundle", "exec", "rails", "server"]
