env: dev

replicas: 2


rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1
image:
  identifier: ${artifact.metadata.image}
  imagePullPolicy: Always
resources:
  cpuLimit: 1500m
  memLimit: 3500Mi
  cpuRequest: 800m
  memRequest: 3000Mi

service:
  http:
    externalPort: 80
    internalPort: 3000

